### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by Nautigsam** [Kolifanes/plugin.video.youtube#110]
I got this error in the log. It occurs when I accepted the application on youtube.com/activate.

```
NOTICE: [plugin.video.youtube] Running: YouTube (5.2.1) on Jarvis (16.1) with Python 2.7.12
09:20:21 T:1285542816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: string index out of range
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 157, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 500, in on_root
                                                yt_login.process(mode, self, context, re_match, False)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_login.py", line 123, in process
                                                access_token = '%s|%s' % (access_tokens[0], access_token_kodi)
                                            IndexError: string index out of range
                                            -->End of Python script error report<--
09:20:21 T:1948774400   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
09:20:21 T:1948774400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
```

**Comment by Nautigsam** [comment]
My bad, it is fixed in the latest version.
