### ISSUE TITLE
Error when Enable setup wizard -> Choose region and language

### ISSUE THREAD

**Issue by kienhg96** [Kolifanes/plugin.video.youtube#114]
Here is my log when I run setup wizard and choose region and language
```
09:00:09 T:4028   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'items'
                                            Traceback (most recent call last):
                                              File "C:\Users\hoangkien\AppData\Roaming\Kodi\addons\plugin.video.youtube\default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "C:\Users\hoangkien\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\kodion\runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "C:\Users\hoangkien\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\kodion\impl\xbmc\xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "C:\Users\hoangkien\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\kodion\abstract_provider.py", line 113, in navigate
                                                self._process_wizard(context)
                                              File "C:\Users\hoangkien\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\kodion\abstract_provider.py", line 100, in _process_wizard
                                                wizard_step[0](*wizard_step[1])
                                              File "C:\Users\hoangkien\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube\helper\yt_setup_wizard.py", line 49, in process
                                                _process_language(provider, context)
                                              File "C:\Users\hoangkien\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube\helper\yt_setup_wizard.py", line 14, in _process_language
                                                items = json_data['items']
                                            KeyError: 'items'
                                            -->End of Python script error report<--
```

**Comment by jdf76** [comment]
What language and region are you trying?

**Comment by anxdpanic** [comment]
It's an uncaught quota error. Can try a different key set (or personal keys) or different time of day to go through the wizard

**Comment by kienhg96** [comment]
@jdf76, I tried to select Vietnamese, 
@anxdpanic, Yesterday, it worked fine. (I didn't change different key)
Thanks.
