### ISSUE TITLE
AttributeError breaks most of it

### ISSUE THREAD

**Issue by cobrafast** [Kolifanes/plugin.video.youtube#123]
Today, seemingly randomly, the plugin stopped working for the most part.
Signing in and out of YouTube accounts works, but none of the other menu items do.
The error box says to look at the log, which says the following:

```
11:46:16 T:140686938593024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'XbmcPluginSettings' object has no attribute 'is_override_view_enabled'
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 59, in run
                                                if context.get_settings().is_override_view_enabled():
                                            AttributeError: 'XbmcPluginSettings' object has no attribute 'is_override_view_enabled'
                                            -->End of Python script error report<--
```

I tried the clear/delete options from the plugin config as well as reinstalling but nothing helped.

Kodi version 16.1 (16.1-5 arch package version)

How can I get it to work again?

**Comment by cobrafast** [comment]
Downgrading to add-on version 5.2.1 from local package cache seems to have helped.
But this surely can't be the proper solution, right?

**Comment by sanlor** [comment]
I'm having the same issue with the same log message (Youtube app complains about error even before logging in with my account).

```
01:47:40  84.331276 T:1751380896  NOTICE: [plugin.video.youtube] Running: YouTube (5.3.5) on Jarvis (16.1) with Python 2.7.11
01:47:40  84.914070 T:1751380896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'XbmcPluginSettings' object has no attribute 'is_override_view_enabled'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 59, in run
                                                if context.get_settings().is_override_view_enabled():
                                            AttributeError: 'XbmcPluginSettings' object has no attribute 'is_override_view_enabled'
                                            -->End of Python script error report<--
```

I manually installed 5.3.4 and it worked fine for me.

Kodi 16.1 (Librelec 7.0.2)

**Comment by radzikem** [comment]
Exactly the same on my side. I noticed that Youtube plugin updated to v5.3.5 today morning and after this update it stopped working. In log I have the same error:

```
10:29:18 2122.990479 T:1740633152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'XbmcPluginSettings' object has no attribute 'is_override_view_enabled'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 59, in run
                                                if context.get_settings().is_override_view_enabled():
                                            AttributeError: 'XbmcPluginSettings' object has no attribute 'is_override_view_enabled'
                                            -->End of Python script error report<--
```
Version 5.3.4 installed manually from zip works fine.

**Comment by anxdpanic** [comment]
Something went wrong during the 5.3.5 PR, 5.3.6 is on official now which will resolve these errors. 

http://mirrors.xbmc.org/addons/krypton/plugin.video.youtube/plugin.video.youtube-5.3.6.zip

**Comment by sanlor** [comment]
Version 5.3.6 works fine for me, thanks!
