### ISSUE TITLE
Live stream doesn't work

### ISSUE THREAD

**Issue by gryphon2411** [Kolifanes/plugin.video.youtube#37]
When attempting to play any YouTube **live stream** video, the video fails to load and one of the following messages appear:

> Youtube error
> Check the log for more information.
> 
> Playback failed
> One or more items failed to play. Check the log for more information about this message.

Log file information in debug mode when attempting to play live stream video:

```
16:18:49 T:2099150416   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
16:18:50 T:2099150416   DEBUG: JSONRPC: Incoming request: { "jsonrpc": "2.0", "method": "Application.GetProperties", "params": {"properties": ["version", "name"]}, "id": 1 }
16:18:50 T:2099150416  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.20.1) on Jarvis (16.1) with Python 2.6.5
16:18:50 T:2099150416   DEBUG: [plugin.video.youtube] Path: "/play/
16:18:50 T:2099150416   DEBUG: [plugin.video.youtube] Params: "{'video_id': u'DekL5q5e9lM'}"
16:18:50 T:2099150416   DEBUG: [plugin.video.youtube] Selecting YouTube config "Jarvis"
16:18:50 T:2099150416   DEBUG: [plugin.video.youtube] User is logged in
16:18:50 T:1989241720   DEBUG: DialogProgress::Open called
16:18:50 T:1989241720   DEBUG: ------ Window Init (DialogProgress.xml) ------
16:18:51 T:2099150416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: unknown yt_format for itag "91"
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 363, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_play.py", line 17, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 80, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/video_info.py", line 324, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/video_info.py", line 549, in _method_get_video_info
                                                return self._load_manifest(url, video_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/video_info.py", line 495, in _load_manifest
                                                raise Exception('unknown yt_format for itag "%s"' % itag)
                                            Exception: unknown yt_format for itag "91"
                                            -->End of Python script error report<--
16:18:51 T:1989241720   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
16:18:51 T:2099150416    INFO: Python script stopped
16:18:51 T:2099150416   DEBUG: Thread LanguageInvoker 2099150416 terminating
16:18:51 T:1989241720   DEBUG:  bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - plugin exited prematurely - terminating
16:18:51 T:1989241720   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=DekL5q5e9lM]
16:18:51 T:1989241720   DEBUG: Playlist Player: one or more items failed to play... aborting playback
```

I find it important to let you know guys.
BTW, great plugin! Thank you very much for it!

**Comment by h0d3nt3uf3l** [comment]
Good music taste :)
The problem is there is no "orginal" url, only a Dash-mpd-url offered. Such a URL isn't implemented yet, but we're working on it.
BTW we only maintaining it, sadly the main developer was left us because of private reasons.

**Comment by gryphon2411** [comment]
Thank you very much for your replay, that's pretty sad to hear but it seems that you guys are doing a great job in maintaining it!

I'm glad to hear that there is a consideration for this feature.

Unfortunately, If I had time I would help you guys and commit it myself.

I'm looking forward to try it in the future, Good luck fellas!

**Comment by misty-** [comment]
@Eido95 - In your log it looks like you're running 5.1.20.1. Starting with ver 5.1.20.2 a live stream itag91 patch was released. Bumping up to 5.1.20.2 and higher will resolve this live stream problem.
