### ISSUE TITLE
Sign In Not Working on Krypton -- Known Issue 

### ISSUE THREAD

**Issue by emouawad** [Kolifanes/plugin.video.youtube#54]
Sign In to YouTube not working on Krypton (Kodi V17).
Everything works as expected, expect i can't sign in, the pop up automatically dismisses itself without signing me in.

**Comment by kampanita** [comment]
I suffered the same issue and resolved it just deleting plugin folder
contents at user_data and trying again

Agurrak, Kepa

---

iNKuBo - _Punk Rock de la Margen Izkierda del puto Nervión_

http://www.inkubopunk.org

---

_Sólo hay 10 tipos de personas en la vida. Las que entienden el binario y
las que no._

**Comment by jdf76** [comment]
This is a known issue and stated in the first post on the forum.

Jeff

**Comment by jdf76** [comment]
This is a known issue as stated in the first post in the forum.

**Comment by Rudd-O** [comment]
Sign In is not working on ANYTHING:

```
23:44:25 T:140489537849088  NOTICE: [plugin.video.youtube] Running: YouTube (5.2.1) on Jarvis (16.1) with Python 2.7.11
23:44:52 T:140489537849088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: string index out of range
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 157, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 500, in on_root
                                                yt_login.process(mode, self, context, re_match, False)
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_login.py", line 123, in process
                                                access_token = '%s|%s' % (access_tokens[0], access_token_kodi)
                                            IndexError: string index out of range
                                            -->End of Python script error report<--
23:44:52 T:140490552289856   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
23:44:52 T:140490552289856   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
```

Version 5.2.1.  Just started happening to me after update.

**Comment by Rudd-O** [comment]
Through hackery, I have determined that the access_tokens variable in that line is an empty string.  No wonder it blows up.

**Comment by Rudd-O** [comment]
While there's definitely a logic error in the code, my issue was fixed with the following workaround on Kodi 16.1:
1. Go to the main YouTube menu.
2. Select "log out".
3. Log back in again.

That fixed the issue.

**Comment by Rudd-O** [comment]
Clearly the bug happens only when there's some data left over or something.  Note that, when YouTube asked me to log in, and it was not working, YouTube was only asking me to authorize the second app, not the first "YouTube TV" app.  So this may give a clue as to where the bug lies.

**Comment by h0d3nt3uf3l** [comment]
Hey,
I've noticed that error a few days ago but thought i already fixed it. Its because of my autologin if you've a quota issue and I don't thought that one variable could be null.
I'll fix it with a new push to the repo (version 5.2.3)
