### ISSUE TITLE
Endless activation request

### ISSUE THREAD

**Issue by giordy** [Kolifanes/plugin.video.youtube#58]
Hi,

first of all, thanks for your work.
Since yesterday when I start the add-on it asks for activation and to input a code that I see on screen at the url youtube.com/activate.
No matter how many times I follow the procedure and try to complete the activation, I get a notification about some error from youtube and it becomes impossible to perform any search.

**Comment by timmit99** [comment]
Second this error. Reinstalled, and tried to install from a ZIP file with the same results.

**Comment by h0d3nt3uf3l** [comment]
Debuglog would be userfull please

**Comment by nicolasr75** [comment]
I would like to provide the log file but don't know where it is located. I'm using OpenElec on a Rasperry Pi. There is a folder /storage/logfiles which contains zip files with timestamps and each zip file contains these files:
- 01_KODI
- 02_System
- 03_Hardware
- 04_Audio
- 05_Network
- 06_varlog
- 07_input
- 08_Filesystem
- 09_Journal-cur
- 10_Journal-prev

Is one of these files the relevant one?

**Comment by paulnovo** [comment]
@nicolasr75 I found my log in ~/.kodi/temp/kodi.log
@h0d3nt3uf3l I think this is the relevant error I am getting:

```
14:29:31 T:139818390497024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: string index out of range
                                            Traceback (most recent call last):
                                              File "/home/foo/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/foo/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/foo/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in
 run
                                                results = provider.navigate(context)
                                              File "/home/foo/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in na
vigate
                                                result = method(context, re_match)
                                              File "/home/foo/.kodi/addons/pl
ugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 157, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/home/foo/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 500, in on_root
                                                yt_login.process(mode, self, context, re_match, False)
                                              File "/home/foo/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_login.py", line 123, in process
                                                access_token = '%s|%s' % (access_tokens[0], access_token_kodi)
                                            IndexError: string index out of range
                                            -->End of Python script error report<--
```

**Comment by nicolasr75** [comment]
@paulnovo Exactly the same error here in the kodi.log although the paths are based on /storage instead of /home/foo on my RasPi.

**Comment by bcontins** [comment]
I had the same error on a Raspberry Pi 2 running OpenELEC.

```
YouTube (5.2.1) on Jarvis (16.1) with Python 2.7.11
```

I managed to work around it by doing:
- Open YouTube plugin and get activation request
- Cancel activation request (should display the plug-in screen)
- Sign-out
- Sign-in again and activate twice

I got back to a normal state with my subscriptions.

**Comment by jdf76** [comment]
I'm actually in the process of pushing 5.3.3 to the Kodi Repository but. if you feel comfortable upgrading on your on you can download it from 
[plugin.video.youtube-5.3.3.zip](https://github.com/Kolifanes/plugin.video.youtube/files/592890/plugin.video.youtube-5.3.3.zip)
Also if you run Krypton you can use Dash Support.

Jeff

**Comment by CrazyPython** [comment]
The error is "API Quota Exceeded" which is a big hint at what the problem is.
