### ISSUE TITLE
urllib2 .py on Ubuntu 16.10

### ISSUE THREAD

**Issue by adrianf0** [Kolifanes/plugin.video.youtube#74]
After update to Ubuntu 16.10, the plug-in doesn't work anymore:

00:04:39 T:140440892319488  NOTICE: [plugin.video.youtube] Running: YouTube (5.2.2) on Jarvis (16.1) with Python 2.7.12+
00:04:39 T:140440892319488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 0] Error>
                                            Traceback (most recent call last):
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(**provider**)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                **RUNNER**.run(provider, context)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 157, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 503, in on_root
                                                self.get_client(context)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 153, in get_client
                                                refresh_tokens[0])
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/login_client.py", line 151, in refresh_token_tv
                                                grant_type=grant_type)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/login_client.py", line 181, in refresh_token
                                                result = requests.post(url, data=post_data, headers=headers, verify=False)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 184, in post
                                                return _request('POST', url, data=data, json=json, *_kwargs)
                                              File "/home/afiergol/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 155, in _request
                                                response = opener.open(request)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 0] Error>
                                            -->End of Python script error report<--
00:04:39 T:140441627000896   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
00:04:39 T:140441627000896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed

**Comment by anxdpanic** [comment]
related to #60 maybe? some solutions are provided there by others which way work for you

**Comment by adrianf0** [comment]
You are right.

> pip install pyopenssl==0.15.1

solves the issue.
