### ISSUE TITLE
Attempting to populate Titan widgets like "My Subscriptions" leads to error

### ISSUE THREAD

**Issue by jordanade** [Kolifanes/plugin.video.youtube#84]
Version 5.2.4 on Jarvis 16.1 with Python 2.7.12. Log:

```
07:14:46 T:140592499570432  NOTICE: [plugin.video.youtube] Running: YouTube (5.2.4) on Jarvis (16.1) with Python 2.7.12
07:14:47 T:140593704564480  NOTICE: Previous line repeats 1 times.
07:14:47 T:140593704564480   ERROR: GetDirectory - Error getting include
07:14:57 T:140592608675584   ERROR: Previous line repeats 3 times.
07:14:57 T:140592499570432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 394, in _on_yt_specials
                                                return yt_specials.process(category, self, context, re_match)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_specials.py", line 242, in process
                                                return _process_new_uploaded_videos_tv(provider, context, re_match)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_specials.py", line 220, in _process_new_uploaded_videos_tv
                                                result.extend(tv.my_subscriptions_to_items(provider, context, json_data))
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/tv.py", line 23, in my_subscriptions_to_items
                                                utils.update_video_infos(provider, context, video_id_dict, channel_items_dict=channel_item_dict)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/utils.py", line 147, in update_video_infos
                                                video_data = resource_manager.get_videos(video_ids)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/resource_manager.py", line 109, in get_videos
                                                result.update(self._update_videos(list_of_50))
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/resource_manager.py", line 68, in _update_videos
                                                video_data = function_cache.get_cached_only(self._get_video_data, unicode(video_id))
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/function_cache.py", line 66, in get_cached_only
                                                data, cache_id = self._get_cached_data(partial_func)
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/function_cache.py", line 56, in _get_cached_data
                                                return self._get(cache_id), cache_id
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/storage.py", line 191, in _get
                                                result = self._execute(False, query, [item_id])
                                              File "/home/jordan/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/storage.py", line 79, in _execute
                                                return self._cursor.execute(query, values)
                                              File "/usr/lib/python2.7/sqlite3/dbapi2.py", line 69, in convert_timestamp
                                                year, month, day = map(int, datepart.split("-"))
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
07:14:58 T:140592516355840   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos_tv/?reload=20161027110412
```

**Comment by jdf76** [comment]
Can you try 5.3.0-alpha4?

**Comment by NovaGL** [comment]
I'm on 5.3.2 and the same thing is happening
